services:
  microservicio_administrador:
    image: mysql
    ports:
      - "8081:8080"  # Mapea el puerto 8081 en el host al 8080 en el contenedor
    environment:
      - "MYSQL_DATABASE:tpe_db_administrador"
      - "MYSQL_ALLOW_EMPTY_PASSWORD:yes"

  microservicio_mantenimiento:
    image: mysql
    ports:
      - "8082:8080"  # Mapea el puerto 8081 en el host al 8080 en el contenedor
    environment:
      - "MYSQL_DATABASE:tpe_db_administrador"
      - "MYSQL_ALLOW_EMPTY_PASSWORD:yes"