services:

  gateway:
    image: mysql
    ports:
      - "3314:3306"  # Mapea el puerto 3314 en el host al 3306 en el contenedor
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  microservicio-administrador:
    image: mysql
    ports:
      - "3307:3306"  # Mapea el puerto 3307 en el host al 3306 en el contenedor
    environment:
      - MYSQL_DATABASE=db_administrador
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  microservicio-mantenimiento:
    image: mysql
    ports:
      - "3308:3306"  # Mapea el puerto 3308 en el host al 3306 en el contenedor
    environment:
      - MYSQL_DATABASE=db_mantenimiento
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  microservicio-cuenta:
    image: mysql
    ports:
      - "3309:3306"  # Mapea el puerto 3309 en el host al 3306 en el contenedor
    environment:
      - MYSQL_DATABASE=db_cuenta
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  microservicio-monopatin:
    image: mysql
    ports:
      - "3310:3306"  # Mapea el puerto 3310 en el host al 3306 en el contenedor
    environment:
      - MYSQL_DATABASE=db_monopatin
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  microservicio-usuario:
    image: mysql
    ports:
      - "3311:3306"  # Mapea el puerto 3311 en el host al 3306 en el contenedor
    environment:
      - MYSQL_DATABASE=db_usuario
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  microservicio-parada:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db_parada
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD:

  microservicio-viaje:
    image: mysql
    ports:
      - "3313:3306"  # Mapea el puerto 3313 en el host al 3306 en el contenedor
    environment:
      - MYSQL_DATABASE=db_viaje
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes


networks:
  my-network:
    driver: bridge