server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: microservicio-administrador
            uri: lb://microservicio-administrador
            predicates:
              - Path=/api/administradores/**
          - id: microservicio-cuenta
            uri: lb://microservicio-cuenta
            predicates:
              - Path=/api/cuentas/**
          - id: microservicio-mantenimiento
            uri: lb://microservicio-mantenimiento
            predicates:
              - Path=/api/mantenimientos/**
          - id: microservicio-monopatin
            uri: lb://microservicio-monopatin
            predicates:
              - Path=/api/monopatines/**
          - id: microservicio-parada
            uri: lb://microservicio-parada
            predicates:
              - Path=/api/paradas/**
          - id: microservicio-usuario
            uri: lb://microservicio-usuario
            predicates:
              - Path=/api/usuarios/**
          - id: microservicio-viaje
            uri: lb://microservicio-viaje
            predicates:
              - Path=/api/viajes/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG