server:
  #port: ${PORT:${SERVER_PORT:0}}
  port: 8082
spring:
  application:
    name: microservicio-administrador
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/db_administrador?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  cloud:
    config:
      enabled: true # Activa la configuración centralizada
      uri: http://localhost:8888 # URL del Config Service
      fail-fast: true # Opcional: para que falle rápido si no encuentra el Config Server
management:
  endpoints:
    web:
      exposure:
        include: "*"
#eureka:
#  client:
#    enabled: false
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      default-zone: http://localhost:8087/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
